### ISSUE TITLE
Documentation would be great

### ISSUE THREAD

**Issue by caspahouzer** [GeraudBourdin/Ti.SvgView#2]
Long waited for svg support on ios.

But don't found out how to use it.

Would be awesome if you provide an example

**Comment by GeraudBourdin** [comment]
hi,

Look at the test app there : https://github.com/GeraudBourdin/Ti.SvgView-TestApp


as simple as it can be : 

var svgView = require('com.geraudbourdin.svgview');
var svg = svgView.createView({
	image: "image.svg",
	width: '350',
	height: '350',
	top: 0,
	left: 0,
	backgroundColor:'white'
});
$.container.add(svg);

there is a function to change the file : 

svg.setImage(image);


that's all :)
I'll provide an example file next week.

**Comment by caspahouzer** [comment]
great!!!
thank you

- Sebastian

**Comment by GeraudBourdin** [comment]
you are welcom. i am glad to see that it can be usefull to someone :)

**Comment by caspahouzer** [comment]
are you kidding? using svg in apps should be a standard for having single files which are can used for every dimension and device

- Sebastian

**Comment by GeraudBourdin** [comment]
i don't understand why neither android or ios do not support this as a native common feature.
By the way, if it seems to be a simple thing with android, with ios it have some issues and all svg tags aren't supported yet. The SVGKit update there lib every week so i will update this ti module as fast as possible if someone is using it. If any svg isn't render correctly you can load it in illustrator or other to fix it (inkscape seems to do the trick). Anyway i would be glad to see it in action so if anyone use it, a screenshot of this could make my day, or my week ! :)

**Comment by caspahouzer** [comment]
thanks man. that's great
